### ISSUE TITLE
ZScript version?

### ISSUE THREAD

**Issue by nar001** [emawind84/QuestZDoom#16]
I'm just curious to know if updating ZScript would be possible? A mod I wanted to try apparently uses 4.8.0, but QuestZDoom reports 4.6.1 which makes it unusable, what would have to be done to update it? Thanks for the help!

**Comment by emawind84** [comment]
Different version of zscript doesn't stop the mod from working, provide more information regarding the mod and the error.
Since different features of zscript have been brought to lzdoom already in a non linear fascion is not possible to know exactly on what version of zscript we are at the moment. The version mismatch is just a warning and it doesn't affect the execution of the game.

**Comment by nar001** [comment]
Well the error was just reporting that the version of ZScript is too old, and it needs 4.8.0, the mod is https://www.doomworld.com/vb/thread/134292

**Comment by emawind84** [comment]
Warning: ZScript version mismatch. 4.8.0 required but only 4.6.1 supported.
**myhouse.pk3:zscript, line 126: Attempt to override non-existent virtual function PlayerLandedMakeGruntSound**

this is the problem, I will see if I can patch the game

**Comment by nar001** [comment]
Thanks, I hope it'll work out!

**Comment by emawind84** [comment]
You can try the latest pre-release, it should work now, please let me know so I close the issue!
@nar001

**Comment by emawind84** [comment]
The map is heavy.
Try this:
In opengl options
- disable the skybox
- disable mirrors options or leave the mirror on and turn off the rest with recursion to 0
- sprite and wall cull distance to 1000
- disable dynamic lights

I close the issue please post on discord so other people might help you get better performance.
