### ISSUE TITLE
Index Controller Joysticks not Being Read

### ISSUE THREAD

**Issue by ObeseCatLord** [emawind84/QuestZDoom#22]
When using my Valve Index controllers with 14-6 or 15-1 on Windows 10, the joysticks aren't usable. In QZDoom's controller settings there is an openvr controller detected, but regardless of the assignments for the axis and the default bindings used they aren't usable in game or for navigating the menus. They can be used as buttons, so the jumping on the bottom of the right joystick works. I have tried setting the Index controllers to be Oculus Touch controllers from within SteamVR's binding settings to see if that would make a difference, but no luck.

**Comment by codeflorist** [comment]
Try the just released [qzd14-dev2](https://github.com/emawind84/QuestZDoom/releases/tag/qzd14-dev2). It works great so far.

Some further tips regarding Index controllers:

For reasons only Valve knows, the `A` buttons are mapped to `Grip` instead of `A` by default in legacy bindings. You need to change this in SteamVR's controller bindings.

Also be sure to remove the `Use as Button` mapping from both Thumb Sticks (to avoid firing click-event on moving sticks).

And you can add a `Use as Button` - `Click` binding for `Right Axis 2 Press` to e.g. the right trackpad to get an additional button.

If you can see a community binding called `QuestZDoom configuration for Index Controller` from `gameflorist`, you can use that to have all these changes and thus maximum available buttons.

**Comment by ObeseCatLord** [comment]
Thank you. Trying the dev version, the left joystick seems to function for moving, but the right joystick still doesn't work. I am using your SteamVR community bindings. Oddly enough the menus don't render in VR, they are just black screens.

**Comment by codeflorist** [comment]
> Thank you. Trying the dev version, the left joystick seems to function for moving, but the right joystick still doesn't work. I am using your SteamVR community bindings. Oddly enough the menus don't render in VR, they are just black screens.

The default setting for the menu is a stationary SteamVR overlay, which is positioned about 2-3 meters over ground. So you'd have to locate it by looking around and up. You can access `VR Options` > `Cinema Mode Options` and set `Cinema Mode` to `Follow Head movement` (the one i'm using), `Follow Main Hand` or `Follow Offhand`. You can also set it to `Disabled`, which gives you the same in-game menu like in GZDoomVR, but it has 2 problems: Vertical look of the surroundings is suddenly tied to your headset, which is quite uncomfortable, and the menu on the monitor-screen is also in VR and not readable well. I'd recommend the `Follow Head/Hand movement` of the `Cinema Mode`.

Regarding right stick: I assume, you mean turning is not working? That's true (I didn't realize it, since i'm using roomscale-turning). I just informed the author in Discord. Other bindings of the right stick (e.g. actions like weapon switching or Strafing/Movement) is working on my end.

**Comment by ObeseCatLord** [comment]
Thank you, Cinema mode works for having the menu show up. The right joystick works fine for strafing, but as you mentioned turning is not working.

**Comment by codeflorist** [comment]
> The right joystick works fine for strafing, but as you mentioned turning is not working.

Emawind has just released [qzd14-dev3](https://github.com/emawind84/QuestZDoom/releases/tag/qzd14-dev3), which fixes this problem.

**Comment by ObeseCatLord** [comment]
This dev build fixes the turning issue. I assume that maxing out the walk and run speed gives you the vanilla speed for for both?

**Comment by codeflorist** [comment]
> This dev build fixes the turning issue. I assume that maxing out the walk and run speed gives you the vanilla speed for for both?

It's a bit complicated. A Discord-user did some math, and apparently a value of 34 should about match vanilla walking speed. Run multiplier in vanilla is 2x, so best to set it at that.
